### ISSUE TITLE
Source Code is not working

### ISSUE THREAD

**Issue by gammers422** [Polarmods/DevX-Cracked#11]
Hi everyone 
I open apk in the Dev-X tool but when I export it as a unity project it gives me 999+ unsolvable errors 
can you please help me to understand that why this is happening and this tool is only meant to get files not working project?

**Comment by Myrkie** [comment]
Devx is not perfect, your expected to have a basic understanding of Csharp to fix any compiler errors.

**Comment by hiyall360** [comment]
It's not meant to generate a fully working Unity Project. It's meant for exploring the game in Unity to see how everything is placed so that you can grab the transforms of every object in a scene, and make your corresponding changes within DevX. If you have enough patience and knowledge, you could restore the game (depending on how complicated and large it is). They show a demonstration of this on their Youtube.
