### ISSUE TITLE
[Request] UnityEX Ultimate

### ISSUE THREAD

**Issue by 10522** [Polarmods/DevX-Cracked#7]
Is it possible to crack the latest version of [UnityEX Ultimate](https://forum.zoneofgames.ru/topic/36240-unityex/)?

UnityEX Ultimate supports new versions of Unity and has features that are not available in DevX.

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
It written on delphi, idk how to crack it, because code in ida is broken.
![image](https://user-images.githubusercontent.com/117515299/200480901-26e9140f-dbbd-48b5-8e77-0d0190f23f1c.png)

And DevX are probably alive:
[Change log in web archive](http://web.archive.org/web/20220921194924/https://devxdevelopment.com/DevXUnityUnpackerChangeLog)
[Change log now](http://devxdevelopment.com/DevXUnityUnpackerChangeLog)
So if DevX release new version, I will update crack

**Comment by ke6DcAiCunUmK4l2YKsYKxVSB7vAiWMj6FCw2md** [comment]
No way to fully crack this program, only some disabled functions, but not Unity 2020+ support. If i try disable lic check for unity 2020+ support result:
![image](https://user-images.githubusercontent.com/117515299/201458921-9d345c32-6371-4a0d-9f16-f9ee291db4e1.png)
So without lic impossibile to fully crack this program

**Comment by ImanCol** [comment]
It literally seems like a crushing version of Devxunity of payment and with more obfuscacion.
